name: inac_data
on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove old files
        uses: JesseTG/rm@v1.0.3
        with:
          path: |
            /econuy_extras/retrieval/faena.xlsx
            /econuy_extras/retrieval/precios.xlsx

      - name: Run script
        run: python econuy_extras/retrieval/get_inac.py

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.1.4