name: taxes_pdf
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install camelot deps
        run: sudo apt install ghostscript python3-tk
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Remove file
        uses: JesseTG/rm@v1.0.2
        with:
          path: /econuy_extras/retrieval/taxes_pdf.csv
      - name: Run script
        run: python econuy_extras/retrieval/taxes_pdf.py
      - name: Add, commit and push
        uses: EndBug/add-and-commit@v7.2.1
