name: taxes_pdf
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Remove file
        uses: JesseTG/rm@v1.0.3
        with:
          path: /econuy_extras/retrieval/taxes_pdf.csv
      - name: Set environment variable
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
      - name: Run script
        run: python econuy_extras/retrieval/get_taxes.py
      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.1.4
