name: taxes_pdf
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install camelot deps
        run: sudo apt install ghostscript python3-tk
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Python deps
        run: pipenv install
      - name: Install own module
        run: pipenv run pip install -e .
      - name: Run script
        run: pipenv run python econuy_extras/retrieval/taxes_pdf.py
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update taxes" -a
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
